<?xml version="1.0"?>
<package format="3">
  <name>go2_piper_description</name>
  <version>0.1.0</version>
  <description>Derived ROS 2 description for the Unitree Go2 with AgileX Piper.</description>
  <maintainer email="lili@robot.com">lili</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>robot_state_publisher</depend>
  <depend>xacro</depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>gazebo_ros2_control</exec_depend>
  <exec_depend>go2_piper_policy_controller</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/share"/>
  </export>
</package>
